WebApplicationMusei/Models/Entities/Citta.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplicationMusei.Models.Entities
{
    public class Citta
    {
        public int Id { get; set; }

        [Display(Name = "Nazione")]
        [Required]
        public int NazioneId { get; set; }
        public Nazione Nazione { get; set; }

        [Required]
        public string Nome { get; set; }
    }
}

WebApplicationMusei/Models/Views/CittaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplicationMusei.Models.Entities;

namespace WebApplicationMusei.Models.Views
{
    public class CittaViewModel : Citta
    {

        public List<Nazione> Nazioni { get; set; }

        public CittaViewModel() { }

        public CittaViewModel(Citta citta, List<Nazione> nazioni) 
        {
            Id = citta.Id;
            Nome = citta.Nome;
            NazioneId = citta.NazioneId;
            Nazioni = nazioni;
        }
    }
}

WebApplicationMusei/Controllers/CittaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplicationMusei.Helpers;
using WebApplicationMusei.Models.Entities;
using WebApplicationMusei.Models.Views;

namespace WebApplicationMusei.Controllers
{
    public class CittaController : Controller
    {



        // GET: CittaController
        public ActionResult Index()
        {
            var model = DatabaseHelper.GetAllCitta();
            return View(model);
        }

        // GET: CittaController/Details/5
        public ActionResult Details(int id)
        {
            var model = DatabaseHelper.GetCittaById(id);
            return View(model);
        }

        // GET: CittaController/Create
        public ActionResult Create()
        {
            var model = new CittaViewModel();
            model.Nazioni = DatabaseHelper.GetAllNazione();

            return View(model);
        }

        // POST: CittaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Citta model)
        {
            try
            {
                if (!ModelState.IsValid || model.NazioneId < 1)
                {
                    var msgKo = "Completa tutti i campi nella maniera corretta<br>";
                    var errors = ModelState.Values.SelectMany(v => v.Errors);
                    var msgKoAggregate = errors.Select(t => t.ErrorMessage).Aggregate((x, y) => $"{x}<br>{y}");
                    ViewData["MsgKo"] = msgKo + msgKoAggregate;
                    var viewModel = new CittaViewModel(model, DatabaseHelper.GetAllNazione());
                    return View(viewModel);
                }
                DatabaseHelper.SaveCitta(model);
                return RedirectToAction(nameof(Index));
            }
            catch
            {

                ViewData["MsgKo"] = "Errore, inserimento non riuscito";
                var viewModel = new CittaViewModel(model, DatabaseHelper.GetAllNazione());
                return View(viewModel);
            }
        }

        // GET: CittaController/Edit/5
        public ActionResult Edit(int id)
        {
            var citta = DatabaseHelper.GetCittaById(id);
            var model = new CittaViewModel();
            model.Nazioni = DatabaseHelper.GetAllNazione();
            model.Id = citta.Id;
            model.Nome = citta.Nome;
            model.NazioneId = citta.NazioneId;
            return View(model);
        }

        // POST: CittaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Citta model)
        {
            try
            {
                if (!ModelState.IsValid || model.NazioneId < 1)
                {
                    var msgKo = "Completa tutti i campi nella maniera corretta<br>";
                    var errors = ModelState.Values.SelectMany(v => v.Errors);
                    //foreach (var error in errors)
                    //{
                    //    msgKo += error.ErrorMessage + "<br>";
                    //}
                    var msgKoAggregate = errors.Select(t => t.ErrorMessage).Aggregate((x, y) => $"{x}<br>{y}");
                    ViewData["MsgKo"] = msgKo + msgKoAggregate;

                }
                else
                {
                    DatabaseHelper.SaveCitta(model);
                    //inseriamo messaggio update completato
                    ViewData["MsgOk"] = "Aggiornamento avvenuto con successo";

                }
            }
            catch
            {
                //inseriamo un eventuale errore
                ViewData["MsgKo"] = "Si è verificato un problema durante l'aggiornamento!";
            }
            var viewModel = new CittaViewModel(model, DatabaseHelper.GetAllNazione());
            return View(viewModel);
        }

        // GET: CittaController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CittaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        public IActionResult Excel()
        {
            var citta = DatabaseHelper.GetAllCitta();
            try
            {
                var content = ExcelHelper.CreateExcelCittaList(citta);
                //facciamo dello stream
                var contentType = "application/octet-stream";

                //creo la response come file
                var fileName = $"citta_{DateTime.Now.ToShortDateString().Replace("/", "_")}.xlsx";
                return File(content, contentType, fileName);

            }
            catch (Exception ex)
            {
                ViewData["MsgKo"] = ex.Message;
            }
            return View();

        }
    }
}

WebApplicationMusei/Controllers/NazioniController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WebApplicationMusei.Helpers;
using WebApplicationMusei.Models.Dtos;
using WebApplicationMusei.Models.Entities;

namespace WebApplicationMusei.Controllers
{
    public class NazioniController : Controller
    {



        // GET: NazioniController
        public ActionResult Index()
        {
            var model = DatabaseHelper.GetAllNazione();
            return View(model);
        }

        // GET: NazioniController/Details/5
        public ActionResult Details(int id)
        {
            var model = DatabaseHelper.GetNazioneById(id);
            return View(model);
        }

        // GET: NazioniController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NazioniController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NazioneDto model) //IFormCollection collection)
        {
            try
            {

                if (!ModelState.IsValid)
                {
                    var msgKo = "Completa tutti i campi nella maniera corretta<br>";
                    var errors = ModelState.Values.SelectMany(v => v.Errors); //recuperiamo la lista di errori
                    var msgKoAggregate = errors.Select(t => t.ErrorMessage).Aggregate((x, y) => $"{x}<br>{y}"); //concatena in una string gli errori
                    ViewData["MsgKo"] = msgKo + msgKoAggregate;
                    return View(model);
                }
                DatabaseHelper.SaveNazione(model);
                if (model.FileFlag != null)
                {
                    var path = PathHelper.GetPathNazione(model.Id);
                    if (!Directory.Exists(path))
                    {
                        //1)creazione cartella nazioni/id in uploads se non esiste con id quello del modello
                        Directory.CreateDirectory(path);
                    }
                    //2)salvare il contenuto di FileFlag nel percorso creato
                    model.ImgBandiera = Guid.NewGuid() + Path.GetExtension(model.FileFlag.FileName);
                    var filePath = path + "\\" + model.ImgBandiera;
                    using (Stream fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        try
                        {
                            model.FileFlag.CopyTo(fileStream);
                        }
                        catch (Exception ex)
                        {

                        }
                    }
                    DatabaseHelper.SaveNazione(model);

                }
                return RedirectToAction(nameof(Index)); //redirect alla lista se non scatta un'eccezione
            }
            catch (Exception ex)
            {
                //ex.Message + ModelBinderAttribute dovranno essere passati alla view
                ViewData["MsgKo"] = ex.Message; //ex.message deve essere loggato e non inviato all'utente, customizzare il msg in Errore server riprova piu tardi
                return View(model);
            }
        }

        // GET: NazioniController/Edit/5
        public ActionResult Edit(int id)
        {
            var model = DatabaseHelper.GetNazioneById(id);
            return View(model);
        }

        // POST: NazioniController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Nazione model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    var msgKo = "Completa tutti i campi nella maniera corretta<br>";
                    var errors = ModelState.Values.SelectMany(v => v.Errors);
                    //foreach (var error in errors)
                    //{
                    //    msgKo += error.ErrorMessage + "<br>";
                    //}
                    var msgKoAggregate = errors.Select(t => t.ErrorMessage).Aggregate((x, y) => $"{x}<br>{y}");
                    ViewData["MsgKo"] = msgKo + msgKoAggregate;
                    return View(model);
                }
                DatabaseHelper.SaveNazione(model);
                //inseriamo messaggio update completato
                ViewData["MsgOk"] = "Aggiornamento avvenuto con successo";
            }
            catch
            {
                //inseriamo un eventuale errore
                ViewData["MsgKo"] = "Si è verificato un problema durante l'aggiornamento!";
            }
            return View(model);
        }

        // GET: NazioniController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: NazioniController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public IActionResult Excel()
        {
            var nazioni = DatabaseHelper.GetAllNazione();
            try
            {
                var content = ExcelHelper.CreateExcelNazioniList(nazioni);
                //facciamo dello stream
                var contentType = "application/octet-stream";

                //creo la response come file
                var fileName = $"nazioni_{DateTime.Now.ToShortDateString().Replace("/", "_")}.xlsx";
                return File(content, contentType, fileName);

            }
            catch (Exception ex)
            {
                ViewData["MsgKo"] = ex.Message;
            }
            return View();

        }
    }
}

WebApplicationMusei/Views/Citta/Create.cshtml
@model WebApplicationMusei.Models.Views.CittaViewModel
@using WebApplicationMusei.Models.Entities 

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Nuova</h1>

<h4>Città</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NazioneId" class="control-label"></label>
                @*<input asp-for="NazioneId" class="form-control" />*@
                <select asp-for="NazioneId" class="form-control"
                        asp-items="@(new SelectList(Model.Nazioni, nameof(Nazione.Id), nameof(Nazione.Nome)))">
                    <option>Seleziona ...</option>
                </select>

                <span asp-validation-for="NazioneId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salva" class="btn btn-primary" />
                @if (ViewData["MsgKo"] != null)
                {
                    <span class="text-danger"> @Html.Raw(ViewData["MsgKo"].ToString())</span>
                }
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplicationMusei/Views/Citta/Details.cshtml
@model WebApplicationMusei.Models.Entities.Citta

@{
    ViewData["Title"] = Model.Nome;
}

<h1>@Model.Nome</h1>

@Html.ActionLink(Model.Nazione.Nome, "Details", "Nazioni", new { id = Model.Nazione.Id })
<img src="~/uploads/nazioni/@Model.Nazione.Id/@Model.Nazione.ImgBandiera" width="200" />

WebApplicationMusei/Views/Citta/Edit.cshtml
@model WebApplicationMusei.Models.Views.CittaViewModel
@using WebApplicationMusei.Models.Entities

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Nazione</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input asp-for="Id" type="hidden" class="form-control" />

            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="NazioneId" class="control-label"></label>
                @*<input asp-for="NazioneId" class="form-control" />*@
                <select asp-for="NazioneId" class="form-control"
                        asp-items="@(new SelectList(Model.Nazioni, nameof(Nazione.Id), nameof(Nazione.Nome)))">
                </select>

                <span asp-validation-for="NazioneId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                @if (ViewData["MsgOk"] != null)
                {
                    <span class="text-success"> @Html.Raw(ViewData["MsgOk"].ToString())</span>
                }
                @if (ViewData["MsgKo"] != null)
                {
                    <span class="text-danger"> @Html.Raw(ViewData["MsgKo"].ToString())</span>
                }
            </div>

        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplicationMusei/Views/Citta/Index.cshtml
@model IEnumerable<WebApplicationMusei.Models.Entities.Citta>

@{
    ViewData["Title"] = "Index";
}

<h1>Città</h1>

<p>
    <a asp-action="Create">Nuovo</a>
</p>
<p>
    <a asp-action="Excel">Scarica excel</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NazioneId)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.ActionLink(item.Nazione.Nome, "Details", "Nazioni", new { id = item.NazioneId })
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Dettaglio", "Details",  new { id = item.Id }) |
                @Html.ActionLink("Elimina", "Delete",  new { id = item.Id })
            </td>
        </tr>
        }
    </tbody>
</table>