WebApplicationMusei/Controllers/CittaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplicationMusei.Helpers;
using WebApplicationMusei.Models.Entities;
using WebApplicationMusei.Models.Views;

namespace WebApplicationMusei.Controllers
{
    public class CittaController : Controller
    {



        // GET: CittaController
        public ActionResult Index()
        {
            var model = DatabaseHelper.GetAllCitta();
            return View(model);
        }

        // GET: CittaController/Details/5
        public ActionResult Details(int id)
        {
            var model = DatabaseHelper.GetCittaById(id);
            return View(model);
        }

        // GET: CittaController/Create
        public ActionResult Create()
        {
            var model = new CittaViewModel();
            model.Nazioni = DatabaseHelper.GetAllNazione();

            return View(model);
        }

        // POST: CittaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Citta model)
        {
            try
            {
                if (!ModelState.IsValid || model.NazioneId < 1)
                {
                    var msgKo = "Completa tutti i campi nella maniera corretta<br>";
                    var errors = ModelState.Values.SelectMany(v => v.Errors);
                    var msgKoAggregate = errors.Select(t => t.ErrorMessage).Aggregate((x, y) => $"{x}<br>{y}");
                    ViewData["MsgKo"] = msgKo + msgKoAggregate;
                    var viewModel = new CittaViewModel(model, DatabaseHelper.GetAllNazione());
                    return View(viewModel);
                }
                DatabaseHelper.SaveCitta(model);
                return RedirectToAction(nameof(Index));
            }
            catch
            {

                ViewData["MsgKo"] = "Errore, inserimento non riuscito";
                var viewModel = new CittaViewModel(model, DatabaseHelper.GetAllNazione());
                return View(viewModel);
            }
        }

        // GET: CittaController/Edit/5
        public ActionResult Edit(int id)
        {
            var citta = DatabaseHelper.GetCittaById(id);
            var model = new CittaViewModel();
            model.Nazioni = DatabaseHelper.GetAllNazione();
            model.Id = citta.Id;
            model.Nome = citta.Nome;
            model.NazioneId = citta.NazioneId;
            return View(model);
        }

        // POST: CittaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Citta model)
        {
            try
            {
                if (!ModelState.IsValid || model.NazioneId < 1)
                {
                    var msgKo = "Completa tutti i campi nella maniera corretta<br>";
                    var errors = ModelState.Values.SelectMany(v => v.Errors);
                    //foreach (var error in errors)
                    //{
                    //    msgKo += error.ErrorMessage + "<br>";
                    //}
                    var msgKoAggregate = errors.Select(t => t.ErrorMessage).Aggregate((x, y) => $"{x}<br>{y}");
                    ViewData["MsgKo"] = msgKo + msgKoAggregate;

                }
                else
                {
                    DatabaseHelper.SaveCitta(model);
                    //inseriamo messaggio update completato
                    ViewData["MsgOk"] = "Aggiornamento avvenuto con successo";

                }
            }
            catch
            {
                //inseriamo un eventuale errore
                ViewData["MsgKo"] = "Si è verificato un problema durante l'aggiornamento!";
            }
            var viewModel = new CittaViewModel(model, DatabaseHelper.GetAllNazione());
            return View(viewModel);
        }

        // GET: CittaController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CittaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        public IActionResult Excel()
        {
            var citta = DatabaseHelper.GetAllCitta();
            try
            {
                var content = ExcelHelper.CreateExcelCittaList(citta);
                //facciamo dello stream
                var contentType = "application/octet-stream";

                //creo la response come file
                var fileName = $"citta_{DateTime.Now.ToShortDateString().Replace("/", "_")}.xlsx";
                return File(content, contentType, fileName);

            }
            catch (Exception ex)
            {
                ViewData["MsgKo"] = ex.Message;
            }
            return View();

        }
    }
}

WebApplicationMusei/Controllers/MuseiController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplicationMusei.Helpers;
using WebApplicationMusei.Models.Entities;

namespace WebApplicationMusei.Controllers
{
    public class MuseiController : Controller
    {
        // GET: MuseiController
        public ActionResult Index()
        {
            var model = DatabaseHelper.GetAllMuseo();
            return View(model);
        }

        // GET: MuseiController/Details/5
        public ActionResult Details(int id)
        {
            var model = DatabaseHelper.GetMuseoById(id);
            return View(model);
        }

        // GET: MuseiController/Create
        public ActionResult Create()
        {
            return View();
        }


        public IActionResult Excel()
        {
            var musei = DatabaseHelper.GetAllMuseo();
            try
            {
                var content = ExcelHelper.CreateExcelMuseiList(musei);
                //facciamo dello stream
                var contentType = "application/octet-stream";

                //creo la response come file
                var fileName = $"musei_{DateTime.Now.ToShortDateString().Replace("/","_")}.xlsx";
                return File(content, contentType, fileName);

            }
            catch (Exception ex)
            {
                ViewData["MsgKo"] = ex.Message;
            }
            return View();

        }


        // POST: MuseiController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MuseiController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: MuseiController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MuseiController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: MuseiController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplicationMusei/Views/Musei/Create.cshtml
@model WebApplicationMusei.Models.Views.MuseoViewModel
@using WebApplicationMusei.Models.Entities 

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Nuova</h1>

<h4>Museo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Denominazione" class="control-label"></label>
                <input asp-for="Denominazione" class="form-control" />
                <span asp-validation-for="Denominazione" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CittaId" class="control-label"></label>
                @*<input asp-for="NazioneId" class="form-control" />*@
                <select asp-for="CittaId" class="form-control"
                        asp-items="@(new SelectList(Model.ListaCitta, nameof(Citta.Id), nameof(Citta.Nome)))">
                    <option>Seleziona ...</option>
                </select>

                <span asp-validation-for="CittaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salva" class="btn btn-primary" />
                @if (ViewData["MsgKo"] != null)
                {
                    <span class="text-danger"> @Html.Raw(ViewData["MsgKo"].ToString())</span>
                }
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplicationMusei/Views/Musei/Details.cshtml
@model WebApplicationMusei.Models.Entities.Museo

@{
    ViewData["Title"] = Model.Denominazione;
}

<h1>@Model.Denominazione</h1>

@Model.Id

WebApplicationMusei/Views/Musei/Edit.cshtml
@model WebApplicationMusei.Models.Views.MuseoViewModel
@using WebApplicationMusei.Models.Entities

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Nazione</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input asp-for="Id" type="hidden" class="form-control" />

            <div class="form-group">
                <label asp-for="Denominazione" class="control-label"></label>
                <input asp-for="Denominazione" class="form-control" />
                <span asp-validation-for="Denominazione" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CittaId" class="control-label"></label>
                @*<input asp-for="NazioneId" class="form-control" />*@
                <select asp-for="CittaId" class="form-control"
                        asp-items="@(new SelectList(Model.ListaCitta, nameof(Citta.Id), nameof(Citta.Nome)))">
                </select>

                <span asp-validation-for="CittaId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                @if (ViewData["MsgOk"] != null)
                {
                    <span class="text-success"> @Html.Raw(ViewData["MsgOk"].ToString())</span>
                }
                @if (ViewData["MsgKo"] != null)
                {
                    <span class="text-danger"> @Html.Raw(ViewData["MsgKo"].ToString())</span>
                }
            </div>

        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplicationMusei/Views/Musei/Index.cshtml
@model IEnumerable<WebApplicationMusei.Models.Entities.Museo>

@{
    ViewData["Title"] = "Index";
}

<h1>Musei</h1>

<p>
    <a asp-action="Create">Nuovo</a>
</p>
<p>
    <a asp-action="Excel">Scarica excel</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Denominazione)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CittaId)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Denominazione)
            </td>
            <td>
                @Html.ActionLink(item.Citta.Nome, "Details", "Citta", new { id = item.Citta.Id })
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
        }
    </tbody>
</table>